# Generated by Django 4.2.7 on 2023-11-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='link_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
