# Generated by Django 4.2.7 on 2023-11-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_services_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='is_home_page',
            field=models.BooleanField(default=False),
        ),
    ]
